version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./prod.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./prod.db.env
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: